### Consider the below code to answer further questions:

In [2]:
import numpy as np
list_ = [ '1' , '2', '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

### Q1. Is there any difference in the data type of variables list_ and array_list?If there is then write a code to print the data types of both the variables.

### Yes, there is a difference in the data type of variables list_ and array_list. list_ is a Python list object while array_list is a NumPy array object.

In [5]:

# printing data types 
print(type(list_)) 
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [7]:
# data type of each element in list_
for e in list_:
    print(type(e))

# data type of each element in array_list
for e in array_list:
    print(type(e))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:

In [10]:
array_list = np.array(object = list_, dtype = int)

### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [15]:
# Yes, following changes will happen in data type: instead of printing <class 'numpy.str_'>, It will print <class 'numpy.int64'> - see the output 
for e in list_:
    print(type(e))
for e in array_list:
    print(type(e))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


## Consider the below code to answer further questions:

In [16]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

### Q4. Write a code to find the following characteristics of variable, num_array:
### (i) shape (ii) size

### Here is the code for printing the characteristics of variable shape and size

In [17]:
# Print the shape of num_array
print(num_array.shape)

# Print the size of num_array
print(num_array.size)

(2, 3)
6


### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

### Creating a 3*3 matrix containing zeros only 


In [19]:
zeros_mat = np.zeros((3,3))
print(zeros_mat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Q6. Create an identity matrix of shape (5,5) using numpy functions?

### identity matrix of shape(5,5) 

In [20]:
identity_mat = np.eye(5)
print(identity_mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
